// <auto-generated />

using ITServicePortfolioManager.DAL.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITServicePortfolioManager.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITServicePackageManager.DAL.Entities.ServicePortfolioResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CompanyIncome")
                        .HasColumnType("double precision");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("ServicePortfolioResults");
                });

            modelBuilder.Entity("ITServicePackageManager.DAL.Entities.TaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CountProvider")
                        .HasColumnType("integer");

                    b.Property<string>("NameAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalHumanResource")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ITServicePackageManager.DAL.Entities.ServicePortfolioResultEntity", b =>
                {
                    b.HasOne("ITServicePackageManager.DAL.Entities.TaskEntity", "Task")
                        .WithOne()
                        .HasForeignKey("ITServicePackageManager.DAL.Entities.ServicePortfolioResultEntity", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ITServicePackageManager.DAL.Entities.PortfolioCellEntity", "Portfolio", b1 =>
                        {
                            b1.Property<long>("ServicePortfolioResultEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("GroupIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("ProviderIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("ServicePortfolioResultEntityId", "Id");

                            b1.ToTable("ServicePortfolioResults");

                            b1.ToJson("Portfolio");

                            b1.WithOwner()
                                .HasForeignKey("ServicePortfolioResultEntityId");
                        });

                    b.OwnsMany("ITServicePackageManager.DAL.Entities.ProviderIncomeEntity", "ProvidersIncome", b1 =>
                        {
                            b1.Property<long>("ServicePortfolioResultEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<double>("Income")
                                .HasColumnType("double precision");

                            b1.HasKey("ServicePortfolioResultEntityId", "Id");

                            b1.ToTable("ServicePortfolioResults");

                            b1.ToJson("ProvidersIncome");

                            b1.WithOwner()
                                .HasForeignKey("ServicePortfolioResultEntityId");
                        });

                    b.Navigation("Portfolio");

                    b.Navigation("ProvidersIncome");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ITServicePackageManager.DAL.Entities.TaskEntity", b =>
                {
                    b.OwnsMany("ITServicePackageManager.DAL.Entities.CommonEntity.GroupServiceEntity", "Groups", b1 =>
                        {
                            b1.Property<long>("TaskEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.HasKey("TaskEntityId", "Id");

                            b1.ToTable("Tasks");

                            b1.ToJson("Groups");

                            b1.WithOwner()
                                .HasForeignKey("TaskEntityId");

                            b1.OwnsMany("ITServicePackageManager.DAL.Entities.ServiceEntity", "Services", b2 =>
                                {
                                    b2.Property<long>("GroupServiceEntityTaskEntityId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("GroupServiceEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<double>("Discount")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("IncomeForProvider")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("LabourIntensity")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Price")
                                        .HasColumnType("integer");

                                    b2.HasKey("GroupServiceEntityTaskEntityId", "GroupServiceEntityId", "Id");

                                    b2.ToTable("Tasks");

                                    b2.ToJson("Services");

                                    b2.WithOwner()
                                        .HasForeignKey("GroupServiceEntityTaskEntityId", "GroupServiceEntityId");
                                });

                            b1.Navigation("Services");
                        });

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
